"""Core/public, v1 base, service/admin and browser-fetch route registration."""
from __future__ import annotations

from collections.abc import Callable, Mapping

from aiohttp import web


def register_core_routes(app: web.Application, h: Mapping[str, Callable]) -> None:
    # ---- Public endpoints ----
    app.router.add_get("/", h["handle_index"])
    app.router.add_get("/health", h["handle_health"])
    app.router.add_get("/v1/version", h["handle_v1_version"])

    # ---- v1 API (auth required) ----
    app.router.add_get("/v1/info", h["handle_v1_info"])
    app.router.add_get("/v1/status", h["handle_v1_status"])
    app.router.add_get("/v1/sysinfo", h["handle_v1_sysinfo"])
    app.router.add_get("/v1/capabilities", h["handle_v1_capabilities"])
    app.router.add_get("/v1/hardware", h["handle_v1_hardware"])
    app.router.add_get("/v1/hwinfo", h["handle_v1_hwinfo"])
    app.router.add_get("/v1/inventory", h["handle_v1_inventory"])
    app.router.add_get("/v1/inventory/registry", h["handle_v1_inventory_registry"])
    app.router.add_get("/v1/ps", h["handle_v1_ps"])
    app.router.add_get("/v1/audit", h["handle_v1_audit"])
    app.router.add_post("/v1/exec", h["handle_v1_exec"])
    app.router.add_post("/v1/kill", h["handle_v1_kill"])
    app.router.add_post("/v1/upload", h["handle_v1_upload"])
    app.router.add_get("/v1/download", h["handle_v1_download"])
    app.router.add_patch("/v1/fs/edit", h["handle_v1_fs_edit"])
    app.router.add_post("/v1/fs/edit/apply", h["handle_v1_fs_edit_apply"])
    app.router.add_post("/v1/fs/edit/rollback", h["handle_v1_fs_edit_rollback"])
    app.router.add_post("/v1/fs/view", h["handle_v1_fs_view"])
    app.router.add_post("/v1/fs/create", h["handle_v1_fs_create"])

    # ---- Dashboard API (auth required) ----
    app.router.add_get("/v1/memory", h["handle_v1_memory"])
    app.router.add_post("/v1/memory", h["handle_v1_memory_set"])
    app.router.add_delete("/v1/memory", h["handle_v1_memory_delete"])
    app.router.add_get("/v1/missions", h["handle_v1_missions"])
    app.router.add_post("/v1/beep", h["handle_v1_beep"])
    app.router.add_get("/v1/doctor", h["handle_v1_doctor"])
    app.router.add_get("/v1/reports", h["handle_v1_reports"])
    app.router.add_get("/v1/browser/search", h["handle_v1_browser_search"])
    app.router.add_get("/v1/browser/read", h["handle_v1_browser_read"])

    # ---- v1.5.0 service/admin/browser utility endpoints ----
    app.router.add_get("/v1/sys/svc", h["handle_v1_sys_svc"])
    app.router.add_get("/v1/service/info", h["handle_v1_service_info"])
    app.router.add_get("/v1/sys/funnel", h["handle_v1_sys_funnel"])
    app.router.add_post("/v1/token/regenerate", h["handle_v1_token_regenerate"])
    app.router.add_post("/v1/tailscale/funnel/{action}", h["handle_v1_tailscale_funnel"])
    app.router.add_get("/v1/tailscale/funnel/{action}", h["handle_v1_tailscale_funnel"])
    app.router.add_post("/v1/cloudflared/tunnel/{action}", h["handle_v1_cloudflared_tunnel"])
    app.router.add_get("/v1/cloudflared/tunnel/{action}", h["handle_v1_cloudflared_tunnel"])
    app.router.add_get("/v1/zerotier/status", h["handle_v1_zerotier_status"])
    app.router.add_post("/v1/zerotier/network/{action}", h["handle_v1_zerotier_network"])
    app.router.add_get("/v1/zerotier/network/{action}", h["handle_v1_zerotier_network"])
    # v3.96.0: ZeroTier Central management (api.zerotier.com).
    app.router.add_get("/v1/zerotier/central/status", h["handle_v1_zerotier_central_status"])
    app.router.add_get("/v1/zerotier/central/networks", h["handle_v1_zerotier_central_networks_list"])
    app.router.add_post("/v1/zerotier/central/networks", h["handle_v1_zerotier_central_networks_create"])
    app.router.add_get("/v1/zerotier/central/networks/{nwid}", h["handle_v1_zerotier_central_network_get"])
    app.router.add_delete("/v1/zerotier/central/networks/{nwid}", h["handle_v1_zerotier_central_network_delete"])
    app.router.add_get("/v1/zerotier/central/networks/{nwid}/members", h["handle_v1_zerotier_central_members_list"])
    app.router.add_post("/v1/zerotier/central/networks/{nwid}/members/{node}", h["handle_v1_zerotier_central_member_update"])
    app.router.add_delete("/v1/zerotier/central/networks/{nwid}/members/{node}", h["handle_v1_zerotier_central_member_delete"])
    app.router.add_get("/v1/tunnels/status", h["handle_v1_tunnels_status"])
    app.router.add_get("/v1/tunnels/active", h["handle_v1_tunnels_active"])
    app.router.add_post("/v1/tunnels/start", h["handle_v1_tunnels_start"])
    app.router.add_post("/v1/tunnels/stop", h["handle_v1_tunnels_stop"])
    # --- v3.85.0: auto-update ---
    app.router.add_get("/v1/admin/update/status",   h["handle_v1_admin_update_status"])
    app.router.add_post("/v1/admin/update/check",   h["handle_v1_admin_update_check"])
    app.router.add_post("/v1/admin/update/apply",   h["handle_v1_admin_update_apply"])
    app.router.add_post("/v1/admin/update/restart", h["handle_v1_admin_update_restart"])
    # --- Mobile (Android via ADB) ---
    app.router.add_get("/v1/mobile/devices", h["handle_v1_mobile_devices"])
    app.router.add_get("/v1/mobile/{serial}/info", h["handle_v1_mobile_info"])
    app.router.add_get("/v1/mobile/{serial}/screenshot", h["handle_v1_mobile_screenshot"])
    app.router.add_post("/v1/mobile/{serial}/tap", h["handle_v1_mobile_tap"])
    app.router.add_post("/v1/mobile/{serial}/swipe", h["handle_v1_mobile_swipe"])
    app.router.add_post("/v1/mobile/{serial}/type", h["handle_v1_mobile_type"])
    app.router.add_post("/v1/mobile/{serial}/key", h["handle_v1_mobile_key"])
    app.router.add_get("/v1/mobile/{serial}/key", h["handle_v1_mobile_key"])
    app.router.add_post("/v1/mobile/{serial}/shell", h["handle_v1_mobile_shell"])
    app.router.add_get("/v1/mobile/{serial}/packages", h["handle_v1_mobile_packages"])
    app.router.add_post("/v1/mobile/{serial}/gesture", h["handle_v1_mobile_gesture"])
    app.router.add_get("/v1/mobile/{serial}/gesture", h["handle_v1_mobile_gesture"])
    app.router.add_get("/v1/mobile/{serial}/ui", h["handle_v1_mobile_ui"])
    app.router.add_post("/v1/mobile/{serial}/tap_by", h["handle_v1_mobile_tap_by"])
    app.router.add_get("/v1/mobile/helpers/status", h["handle_v1_mobile_helpers_status"])
    app.router.add_post("/v1/mobile/{serial}/helpers/install", h["handle_v1_mobile_helpers_install"])
    app.router.add_get("/v1/mobile/{serial}/ime", h["handle_v1_mobile_ime_status"])
    app.router.add_post("/v1/mobile/{serial}/ime/set", h["handle_v1_mobile_ime_set"])
    app.router.add_post("/v1/mobile/{serial}/ime/reset", h["handle_v1_mobile_ime_reset"])
    app.router.add_post("/v1/mobile/{serial}/paste", h["handle_v1_mobile_paste"])
    app.router.add_get("/v1/mobile/{serial}/sensors", h["handle_v1_mobile_sensors"])
    app.router.add_post("/v1/mobile/{serial}/scroll", h["handle_v1_mobile_scroll"])
    app.router.add_post("/v1/mobile/{serial}/key_combo", h["handle_v1_mobile_key_combo"])
    app.router.add_post("/v1/mobile/pair", h["handle_v1_mobile_pair"])
    app.router.add_post("/v1/mobile/connect", h["handle_v1_mobile_connect"])
    app.router.add_post("/v1/mobile/disconnect", h["handle_v1_mobile_disconnect"])
    app.router.add_post("/v1/mobile/apk/prepare", h["handle_v1_mobile_apk_prepare"])
    app.router.add_get("/v1/mobile/apk/prepare", h["handle_v1_mobile_apk_prepare"])
    app.router.add_post("/v1/mobile/{serial}/apk/install", h["handle_v1_mobile_apk_install"])
    app.router.add_post("/v1/mobile/{serial}/batch", h["handle_v1_mobile_batch"])
    app.router.add_post("/v1/mobile/{serial}/camera/launch",  h["handle_v1_mobile_camera_launch"])
    app.router.add_post("/v1/mobile/{serial}/camera/shutter", h["handle_v1_mobile_camera_shutter"])
    app.router.add_get("/v1/mobile/{serial}/camera/photos",   h["handle_v1_mobile_camera_photos"])
    app.router.add_post("/v1/mobile/{serial}/camera/pull",    h["handle_v1_mobile_camera_pull"])
    app.router.add_post("/v1/mobile/{serial}/camera/capture", h["handle_v1_mobile_camera_capture"])
    app.router.add_post("/v1/mobile/apk/upload",  h["handle_v1_mobile_apk_upload"])
    app.router.add_post("/v1/mobile/{serial}/recording/sync",   h["handle_v1_mobile_record_sync"])
    app.router.add_post("/v1/mobile/{serial}/recording/start",  h["handle_v1_mobile_record_start"])
    app.router.add_post("/v1/mobile/recording/{rec_id}/stop",   h["handle_v1_mobile_record_stop"])
    app.router.add_get("/v1/mobile/{serial}/recordings",         h["handle_v1_mobile_record_list"])
    app.router.add_get("/v1/mobile/recording/{rec_id}",          h["handle_v1_mobile_record_pull"])
    app.router.add_post("/v1/mobile/{serial}/recording/purge",   h["handle_v1_mobile_record_purge"])
    app.router.add_get("/v1/mobile/{serial}/mirror",         h["handle_v1_mobile_mirror_ws"])
    app.router.add_get("/v1/mobile/mirror/stats",            h["handle_v1_mobile_mirror_stats"])
    app.router.add_post("/v1/mobile/{serial}/mirror/stop",   h["handle_v1_mobile_mirror_stop"])
    # v3.84.4: expanded camera control surface.
    app.router.add_get("/v1/mobile/{serial}/camera/controls",       h["handle_v1_mobile_camera_controls"])
    app.router.add_post("/v1/mobile/{serial}/camera/mode",          h["handle_v1_mobile_camera_mode"])
    app.router.add_post("/v1/mobile/{serial}/camera/lens",          h["handle_v1_mobile_camera_lens"])
    app.router.add_post("/v1/mobile/{serial}/camera/zoom",          h["handle_v1_mobile_camera_zoom"])
    app.router.add_post("/v1/mobile/{serial}/camera/flash",         h["handle_v1_mobile_camera_flash"])
    app.router.add_post("/v1/mobile/{serial}/camera/record/start",  h["handle_v1_mobile_camera_record_start"])
    app.router.add_post("/v1/mobile/{serial}/camera/record/stop",   h["handle_v1_mobile_camera_record_stop"])
    # v3.84.5: transport fallback (USB <-> wireless ADB).
    app.router.add_get("/v1/mobile/transport",                       h["handle_v1_mobile_transport_status"])
    app.router.add_get("/v1/mobile/{serial}/transport",              h["handle_v1_mobile_transport_status"])
    app.router.add_post("/v1/mobile/{serial}/transport/tcp/enable",  h["handle_v1_mobile_transport_tcp_enable"])
    app.router.add_post("/v1/mobile/{serial}/transport/tcp/disable", h["handle_v1_mobile_transport_tcp_disable"])
    app.router.add_post("/v1/restart", h["handle_v1_restart"])
    app.router.add_get("/v1/webhooks", h["handle_v1_webhooks_get"])
    app.router.add_post("/v1/webhooks", h["handle_v1_webhooks_set"])
    app.router.add_get("/v1/config", h["handle_v1_config"])
    app.router.add_get("/v1/browser/dump", h["handle_v1_browser_dump"])
    app.router.add_get("/v1/browser/fetch", h["handle_v1_browser_fetch"])
    app.router.add_get("/v1/browser/head", h["handle_v1_browser_head"])
    # --- v3.86.0: multi-agent sessions ---
    app.router.add_post("/v1/agents",              h["handle_v1_agents_create"])
    app.router.add_get("/v1/agents",               h["handle_v1_agents_list"])
    app.router.add_get("/v1/agents/{agent_id}",    h["handle_v1_agents_get"])
    app.router.add_delete("/v1/agents/{agent_id}", h["handle_v1_agents_delete"])

