#!/usr/bin/env python3
"""Book of Eternity Arena Relay CLI (boe-arena-relay).

A drop-in pseudo-CLI for Book of Eternity's ConPTY GM Bridge.
Sits in the interactive ConPTY session, receives bracketed-paste dispatch
prompts from game_master_daemon.ps1, places them into arena_relay_inbox.json,
renders the active 'Working' status to keep the daemon harness busy, and
returns to idle ('›') once ready/turn_complete.json is generated by the AI agent.

Usage:
    boe-arena-relay [--session-dir PATH]
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

from arena.constants import VERSION
from arena.game import boe_relay


def _strip_bracketed_paste(text: str) -> str:
    """Remove terminal bracketed-paste escape sequences."""
    text = text.replace("\x1b[200~", "").replace("\x1b[201~", "")
    return text.strip()


def run_relay_loop(session_dir: Path, poll_interval: float = 0.5) -> int:
    """Run the interactive ConPTY relay REPL."""
    print("=" * 60)
    print(f"Book of Eternity · Skainet Relay v{VERSION}")
    print(f"session: {session_dir.resolve()}")
    print("state:   READY")
    print("=" * 60)
    sys.stdout.write("› ")
    sys.stdout.flush()

    while True:
        try:
            line = sys.stdin.readline()
            if not line:
                # EOF
                time.sleep(1.0)
                continue

            raw_prompt = _strip_bracketed_paste(line)
            if not raw_prompt:
                sys.stdout.write("› ")
                sys.stdout.flush()
                continue

            # Ingest prompt
            packet = boe_relay.write_inbox(session_dir, raw_prompt)

            t_num = packet.get("turnNumber") or "?"
            r_id = packet.get("requestId") or ""
            kind = packet.get("kind") or "turn"

            print(f"\n[Relay] Ingested {kind} packet (turn #{t_num}, request: {r_id})")
            print(f"Working on {kind} #{t_num}")
            print("esc to interrupt\n")
            sys.stdout.flush()

            # Poll for turn completion on disk
            start_poll = time.time()
            complete_path = boe_relay.resolve_session_path(session_dir, boe_relay.READY_COMPLETE_FILE)
            error_path = boe_relay.resolve_session_path(session_dir, boe_relay.READY_ERROR_FILE)
            repair_path = boe_relay.resolve_session_path(session_dir, boe_relay.REPAIR_READY_FILE)

            # Wait until ready file or bootstrap timeout
            if kind == "bootstrap":
                time.sleep(1.0)
                print("[Relay] Bootstrap acknowledged.")
            else:
                while True:
                    if complete_path.exists() and complete_path.stat().st_mtime >= start_poll - 2.0:
                        print(f"\n[Relay] Turn #{t_num} complete signal detected.")
                        break
                    if error_path.exists() and error_path.stat().st_mtime >= start_poll - 2.0:
                        print(f"\n[Relay] Turn #{t_num} error signal detected.")
                        break
                    if repair_path.exists() and repair_path.stat().st_mtime >= start_poll - 2.0:
                        print(f"\n[Relay] Turn #{t_num} repair signal detected.")
                        break
                    time.sleep(poll_interval)

            print("state: READY")
            sys.stdout.write("› ")
            sys.stdout.flush()

        except (KeyboardInterrupt, EOFError):
            print("\n[Relay] Shutdown signal received. Exiting.")
            break
        except Exception as e:
            print(f"\n[Relay Error] {e}")
            sys.stdout.write("› ")
            sys.stdout.flush()

    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Book of Eternity Arena Relay CLI")
    parser.add_argument(
        "--session-dir",
        type=Path,
        default=Path.cwd(),
        help="Path to game_session directory (default: current working directory)",
    )
    args = parser.parse_args(argv)
    return run_relay_loop(args.session_dir)


if __name__ == "__main__":
    sys.exit(main())
