"""Public endpoint listing for the bridge index."""
from __future__ import annotations

PUBLIC_ENDPOINTS = [
    "/health", "/v1/version", "/v1/info", "/v1/status", "/v1/sysinfo",
    "/v1/capabilities", "/v1/hardware", "/v1/hwinfo", "/v1/inventory?section=&format=text|json",
    "/v1/ps", "/v1/audit?lines=100", "/v1/audit/stats",
    "POST /v1/exec", "POST /v1/kill",
    "POST /v1/upload?path=", "GET /v1/download?path=",
    "GET /v1/memory?q=", "POST /v1/memory",
    "GET /v1/missions", "GET /v1/mission/show?name=", "GET /v1/mission/status?name=", "GET /v1/mission/report?name=", "GET /v1/mission/history?name=", "GET /v1/mission/lineage?name=", "GET /v1/mission/family?name=", "GET /v1/mission/catalog?q=&state=&template=&has_report=&limit=&offset=", "GET /v1/mission/schedules?action=&enabled=&due_only=&limit=", "GET /v1/mission/templates",
    "POST /v1/mission/compose", "POST /v1/mission/propose", "POST /v1/mission/create", "POST /v1/mission/run", "POST /v1/mission/rerun", "POST /v1/mission/recover", "POST /v1/mission/followup", "POST /v1/mission/iterate", "POST /v1/mission/schedules", "DELETE /v1/mission/schedules", "POST /v1/mission/schedules/tick",
    "GET /v1/reports", "GET /v1/doctor", "POST /v1/beep",
    "GET /v1/browser/search?q=", "GET /v1/browser/read?url=",
    "GET /v1/browser/dump?url=", "GET /v1/browser/fetch?url=",
    "GET /v1/browser/head?url=",
    "GET /v1/browser/cdp/status", "POST /v1/browser/cdp/connect", "POST /v1/browser/cdp/disconnect",
    "POST /v1/browser/cdp/navigate", "GET /v1/browser/cdp/screenshot", "GET /v1/browser/cdp/dom",
    "POST /v1/browser/cdp/eval", "POST /v1/browser/cdp/click (selector|x,y)", "POST /v1/browser/cdp/type",
    "GET /v1/desktop/screenshot", "POST /v1/desktop/click", "POST /v1/desktop/type",
    "POST /v1/desktop/key", "POST /v1/desktop/mouse", "GET /v1/desktop/windows",
    "GET /v1/desktop/active_window", "POST /v1/desktop/focus",
    "POST /v1/desktop/window_action", "POST /v1/desktop/resolve_text_target", "POST /v1/desktop/text_action",
    "GET /v1/control/status", "POST /v1/control/pause", "POST /v1/control/resume", "POST /v1/control/revoke",
    "GET /v1/browser/cdp/tabs", "POST /v1/browser/cdp/tabs/new", "POST /v1/browser/cdp/tabs/close",
    "POST /v1/browser/cdp/tabs/activate", "GET/POST/DELETE /v1/browser/cdp/cookies",
    "POST /v1/browser/cdp/cookies/clear", "GET/POST /v1/browser/cdp/cookies/profiles",
    "POST /v1/browser/cdp/network/start", "POST /v1/browser/cdp/network/stop",
    "GET /v1/browser/cdp/network/requests", "GET /v1/browser/cdp/network/har",
    "POST /v1/browser/cdp/intercept/start", "POST /v1/browser/cdp/intercept/stop",
    "POST/DELETE/GET /v1/browser/cdp/intercept/rule|rules",
    "GET /v1/browser/cdp/session/check", "GET/POST /v1/cdp/* aliases",
    "GET /v1/recall?q=&top=5", "GET /v1/recall/digest",
    "GET /v1/tasks?status=&limit=20", "POST /v1/tasks", "POST /v1/tasks/clean",
    "GET /v1/skills", "POST /v1/skills/run",
    "GET /v1/hooks", "GET /v1/agents",
    "GET /v1/subagents", "POST /v1/subagents/spawn",
    "GET /v1/sys/svc", "GET /v1/sys/funnel",
    "GET /v1/service/info",
    "POST /v1/token/regenerate",
    "POST /v1/tailscale/funnel/{start|stop|status}",
    "POST /v1/restart",
    "GET /v1/config",
    "GET /v1/metrics",
    "/gui", "POST /mcp", "DELETE /mcp",
    "GET /sse", "POST /messages", "GET /ws",
    "/gateway", "/gateway/tools", "POST /run", "POST /tool",
]
