const ARENA_SITE_ADAPTERS = [
  {
    name: 'chatgpt',
    hosts: ['chat.openai.com', 'chatgpt.com'],
    messageSelectors: ['[data-message-author-role="assistant"]', 'article[data-testid^="conversation-turn-"]', 'main article'],
    composerSelectors: ['#prompt-textarea', 'textarea[placeholder*="Message"]', 'div#prompt-textarea[contenteditable="true"]'],
    submitSelectors: ['button[data-testid="send-button"]', 'button[data-testid*="send"]', 'form button[type="submit"]', 'button[type="submit"]', 'button[aria-label*="Send"]', 'button[aria-label*="Отправ"]', 'button svg[viewBox][aria-hidden="true"]'],
  },
  {
    name: 'claude',
    hosts: ['claude.ai'],
    messageSelectors: ['[data-test-render-count]'],
    composerSelectors: ['div.ProseMirror[contenteditable="true"]', 'div[contenteditable="true"]', 'textarea'],
    submitSelectors: ['button[aria-label="Send message"]', 'button[aria-label*="Send"]', 'fieldset button[type="submit"]', 'button[type="submit"]'],
  },
  {
    name: 'gemini',
    hosts: ['gemini.google.com', 'aistudio.google.com'],
    messageSelectors: ['message-content', 'model-response', 'pre', 'code', '[class*=\"code\"]', 'main article', 'main'],
    composerSelectors: ['rich-textarea div[contenteditable="true"]', 'textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[aria-label*="Send"]', 'button[aria-label*="Send message"]', 'button.send-button', 'button[mattooltip*="Send"]', 'button[aria-label*="Run"]', 'button[type="submit"]'],
  },
  {
    name: 'perplexity',
    hosts: ['www.perplexity.ai', 'perplexity.ai'],
    messageSelectors: ['main [data-testid]', 'main article', 'main'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[aria-label*="Submit"]', 'button[aria-label*="Send"]', 'button[type="submit"]'],
  },
  {
    name: 'grok',
    hosts: ['grok.com'],
    messageSelectors: ['main article', 'main [data-testid]', 'main'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[aria-label*="Send"]', 'button[type="submit"]'],
  },
  {
    name: 'openrouter',
    hosts: ['openrouter.ai'],
    messageSelectors: ['main article', 'main [data-testid]', 'main'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[aria-label*="Send"]', 'button[type="submit"]'],
  },
  {
    name: 'deepseek',
    hosts: ['chat.deepseek.com'],
    messageSelectors: ['main article', 'main [data-testid]', 'main'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[aria-label*="Send"]', 'button[type="submit"]'],
  },
  {
    name: 'kimi',
    hosts: ['kimi.com'],
    messageSelectors: ['main article', 'main [data-testid]', 'main'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[aria-label*="Send"]', 'button[type="submit"]'],
  },
  {
    name: 'qwen',
    hosts: ['chat.qwen.ai'],
    messageSelectors: ['main article', 'main [data-testid]', 'main'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[aria-label*="Send"]', 'button[type="submit"]'],
  },
  {
    name: 't3chat',
    hosts: ['t3.chat'],
    messageSelectors: ['main article', 'main [data-testid]', 'main', 'pre', 'code'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[type="submit"]', 'button[aria-label*="Send"]', 'button[aria-label*="Отправ"]'],
  },
  {
    name: 'zai',
    hosts: ['chat.z.ai'],
    messageSelectors: ['main article', 'main [data-testid]', 'main', 'pre', 'code'],
    composerSelectors: ['textarea', '[contenteditable="true"]'],
    submitSelectors: ['button[type="submit"]', 'button[aria-label*="Send"]', 'button[aria-label*="Отправ"]'],
  },
  {
    name: 'generic',
    hosts: [],
    messageSelectors: ['article', 'main', 'section', 'pre', 'code'],
    composerSelectors: ['textarea', 'input[type="text"]', '[contenteditable="true"]'],
    submitSelectors: ['button[type="submit"]', 'button[aria-label*="Send"]'],
  },
];
