"""MCP tool metadata registry."""
from __future__ import annotations

MCP_TOOLS = [
    {"name": "ping", "description": "Return pong (liveness)",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "echo", "description": "Echo arguments back",
     "inputSchema": {"type": "object", "properties": {"text": {"type": "string"}}, "required": ["text"]}},
    {"name": "exec", "description": "Run shell command outside bridge cgroup (via sd-exec)",
     "inputSchema": {"type": "object", "properties": {
         "cmd": {"type": "string"}, "timeout": {"type": "integer", "default": 60}},
         "required": ["cmd"]}},
    {"name": "fs.read", "description": "Read file contents (utf-8)",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string"}, "max_bytes": {"type": "integer", "default": 200000}},
         "required": ["path"]}},
    {"name": "fs.write", "description": "Write file (utf-8). Creates directories.",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string"}, "content": {"type": "string"}}, "required": ["path", "content"]}},
    {"name": "fs.list", "description": "List directory entries",
     "inputSchema": {"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]}},
    {"name": "fs.edit", "description": "Find-and-replace in a text file (str_replace_editor semantics). old_text must be unique unless replace_all=true.",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string"},
         "old_text": {"type": "string"},
         "new_text": {"type": "string"},
         "replace_all": {"type": "boolean", "default": False}},
         "required": ["path", "old_text", "new_text"]}},
    {"name": "fs.view", "description": "View file contents with line numbers. Optional view_range=[start,end] for line range (1-indexed).",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string"},
         "view_range": {"type": "array", "items": {"type": "integer"}, "maxItems": 2}},
         "required": ["path"]}},
    {"name": "fs.create", "description": "Create a new text file. Fails if file already exists (use fs.edit to modify).",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string"},
         "content": {"type": "string"}},
         "required": ["path", "content"]}},
    {"name": "fs.search", "description": "Search file contents by regex pattern. Returns matches with file path, line number, and line content.",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string", "description": "Directory or file to search in"},
         "pattern": {"type": "string", "description": "Regex pattern to search for"},
         "glob": {"type": "string", "description": "Optional file glob filter (e.g. *.py)"},
         "max_results": {"type": "integer", "default": 50},
         "context": {"type": "integer", "default": 0, "description": "Lines of context around each match"},
         "ignore_case": {"type": "boolean", "default": False}},
         "required": ["path", "pattern"]}},
    {"name": "fs.grep", "description": "Alias for fs.search. Search file contents by regex pattern.",
     "inputSchema": {"type": "object", "properties": {
         "path": {"type": "string"},
         "pattern": {"type": "string"},
         "glob": {"type": "string"},
         "max_results": {"type": "integer", "default": 50},
         "context": {"type": "integer", "default": 0},
         "ignore_case": {"type": "boolean", "default": False}},
         "required": ["path", "pattern"]}},
    {"name": "browser.search", "description": "DuckDuckGo search via pure-Python (no chromium)",
     "inputSchema": {"type": "object", "properties": {
         "query": {"type": "string"}, "n": {"type": "integer", "default": 5}},
         "required": ["query"]}},
    {"name": "browser.read", "description": "Readability-extract clean text from URL",
     "inputSchema": {"type": "object", "properties": {"url": {"type": "string"}}, "required": ["url"]}},
    {"name": "browser.shot", "description": "Take headless chromium screenshot via sd-exec",
     "inputSchema": {"type": "object", "properties": {"url": {"type": "string"}}, "required": ["url"]}},
    {"name": "mem.set", "description": "Remember a fact",
     "inputSchema": {"type": "object", "properties": {
         "key": {"type": "string"}, "value": {"type": "string"},
         "tags": {"type": "array", "items": {"type": "string"}}}, "required": ["key", "value"]}},
    {"name": "mem.get", "description": "Recall facts matching query substring",
     "inputSchema": {"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}},
    {"name": "sys.status", "description": "Bridge/services/funnel status",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "skill.list", "description": "List available agent skills",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "skill.run", "description": "Run an agent skill: namespace/name with optional args",
     "inputSchema": {"type": "object", "properties": {
         "name": {"type": "string"}, "args": {"type": "array", "items": {"type": "string"}, "default": []}},
         "required": ["name"]}},
    {"name": "hooks.list", "description": "List configured hooks per event",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "snapshot", "description": "Run system snapshot skill and return JSON path",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "subagent.spawn", "description": "Spawn isolated subagent for delegated work; returns summary",
     "inputSchema": {"type": "object", "properties": {
         "cmd": {"type": "string"}, "name": {"type": "string"},
         "wait": {"type": "boolean", "default": True}, "timeout": {"type": "integer", "default": 300}},
         "required": ["cmd"]}},
    {"name": "subagent.list", "description": "List recent subagents",
     "inputSchema": {"type": "object", "properties": {}}},
    {"name": "memory.recall", "description": "Find relevant facts/snapshots/sessions by query (TF score)",
     "inputSchema": {"type": "object", "properties": {
         "query": {"type": "string"}, "top": {"type": "integer", "default": 5}},
         "required": ["query"]}},
    {"name": "memory.digest", "description": "Compact markdown digest of recent memory (facts/snapshots/subagents)",
     "inputSchema": {"type": "object", "properties": {}}},
]
