"""Mission-related MCP tool metadata."""
from __future__ import annotations

MISSION_MCP_TOOLS = [
    {"name": "mission.templates", "description": "List built-in mission templates for mission composition and execution.", "inputSchema": {"type": "object", "properties": {}}},
    {"name": "mission.status", "description": "Get structured status for a persisted mission by mission id or name.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "name": {"type": "string"}}}},
    {"name": "mission.report", "description": "Read the generated REPORT.md for a persisted mission by mission id or name.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "name": {"type": "string"}}}},
    {"name": "mission.history", "description": "Inspect mission run history and step log summaries for a persisted mission by mission id or name.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "name": {"type": "string"}}}},
    {"name": "mission.lineage", "description": "Inspect mission parent/child lineage, ancestors, descendants, and siblings for a persisted mission.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "name": {"type": "string"}}}},
    {"name": "mission.catalog", "description": "List persisted missions with lifecycle filters such as query, state, template, and report presence.", "inputSchema": {"type": "object", "properties": {"query": {"type": "string"}, "q": {"type": "string"}, "state": {"type": "string"}, "template": {"type": "string"}, "has_report": {"type": "boolean"}, "limit": {"type": "integer", "default": 50}, "offset": {"type": "integer", "default": 0}}}},
    {"name": "mission.compose", "description": "Compose a planner-backed mission draft from a goal, context, and optional mission template.", "inputSchema": {"type": "object", "properties": {"goal": {"type": "string"}, "context": {"type": "string"}, "constraints": {"type": "array", "items": {"type": "string"}}, "max_steps": {"type": "integer", "default": 8}, "memory_profile": {"type": "string"}, "title": {"type": "string"}, "template": {"type": "string"}}, "required": ["goal"]}},
    {"name": "mission.create", "description": "Persist a composed mission draft under the local missions directory.", "inputSchema": {"type": "object", "properties": {"draft": {"type": "object"}, "goal": {"type": "string"}, "context": {"type": "string"}, "constraints": {"type": "array", "items": {"type": "string"}}, "max_steps": {"type": "integer", "default": 8}, "memory_profile": {"type": "string"}, "title": {"type": "string"}, "template": {"type": "string"}, "mission_id": {"type": "string"}, "overwrite": {"type": "boolean", "default": False}}}},
    {"name": "mission.propose", "description": "Run a bounded agentic proposal flow, reflect on it, and return a planner-backed mission draft with optional creation/run.", "inputSchema": {"type": "object", "properties": {"goal": {"type": "string"}, "context": {"type": "string"}, "constraints": {"type": "array", "items": {"type": "string"}}, "max_steps": {"type": "integer", "default": 8}, "max_iterations": {"type": "integer", "default": 4}, "memory_profile": {"type": "string"}, "url": {"type": "string"}, "title": {"type": "string"}, "template": {"type": "string"}, "notes": {"type": "string"}, "create": {"type": "boolean", "default": False}, "run_now": {"type": "boolean", "default": False}, "mission_id": {"type": "string"}, "overwrite": {"type": "boolean", "default": False}, "timeout": {"type": "integer", "default": 180}}, "required": ["goal"]}},
    {"name": "mission.run", "description": "Run a persisted mission by mission_id using the built-in mission manager.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "step": {"type": "integer"}, "timeout": {"type": "integer", "default": 180}}, "required": ["mission_id"]}},
    {"name": "mission.rerun", "description": "Rerun a mission, optionally only the last failed step or a chosen step.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "step": {"type": "integer"}, "failed_only": {"type": "boolean", "default": False}, "timeout": {"type": "integer", "default": 180}}, "required": ["mission_id"]}},
    {"name": "mission.recover", "description": "Build a mission recovery bundle from persisted mission state, with optional rerun and follow-up mission composition.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "notes": {"type": "string"}, "failed_only": {"type": "boolean", "default": True}, "step": {"type": "integer"}, "timeout": {"type": "integer", "default": 180}, "rerun_now": {"type": "boolean", "default": False}, "compose_followup": {"type": "boolean", "default": False}, "create_followup": {"type": "boolean", "default": False}, "followup_goal": {"type": "string"}, "followup_title": {"type": "string"}, "followup_mission_id": {"type": "string"}, "max_steps": {"type": "integer", "default": 8}, "memory_profile": {"type": "string"}, "template": {"type": "string"}, "overwrite": {"type": "boolean", "default": False}}, "required": ["mission_id"]}},
    {"name": "mission.followup", "description": "Compose a next mission from an existing mission's artifacts using agentic analysis.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "goal": {"type": "string"}, "title": {"type": "string"}, "notes": {"type": "string"}, "constraints": {"type": "array", "items": {"type": "string"}}, "max_steps": {"type": "integer", "default": 8}, "max_iterations": {"type": "integer", "default": 4}, "memory_profile": {"type": "string"}, "template": {"type": "string"}, "url": {"type": "string"}, "create": {"type": "boolean", "default": False}, "run_now": {"type": "boolean", "default": False}, "followup_mission_id": {"type": "string"}, "overwrite": {"type": "boolean", "default": False}, "timeout": {"type": "integer", "default": 180}}, "required": ["mission_id"]}},
    {"name": "mission.iterate", "description": "Run a mission iteration loop that combines recovery with optional follow-up mission creation and execution.", "inputSchema": {"type": "object", "properties": {"mission_id": {"type": "string"}, "notes": {"type": "string"}, "failed_only": {"type": "boolean", "default": True}, "step": {"type": "integer"}, "timeout": {"type": "integer", "default": 180}, "rerun_now": {"type": "boolean", "default": False}, "compose_followup": {"type": "boolean", "default": False}, "create_followup": {"type": "boolean", "default": False}, "run_followup": {"type": "boolean", "default": False}, "followup_goal": {"type": "string"}, "followup_title": {"type": "string"}, "followup_mission_id": {"type": "string"}, "constraints": {"type": "array", "items": {"type": "string"}}, "max_steps": {"type": "integer", "default": 8}, "max_iterations": {"type": "integer", "default": 4}, "memory_profile": {"type": "string"}, "template": {"type": "string"}, "url": {"type": "string"}, "overwrite": {"type": "boolean", "default": False}}, "required": ["mission_id"]}},
]

__all__ = ["MISSION_MCP_TOOLS"]
