#!/usr/bin/env python3
"""Render the project-metrics table into README.md between marker comments.

The user asked for a README that shows more than badges -- lines of code and
similar. Numbers typed by hand rot the moment anyone writes code, and a stale
number in a README is a small lie that nobody notices. So they are generated,
and CI checks the rendered block is current.

Two design points worth keeping:

* The block between the markers is EXCLUDED from the line counts. Without that
  the script counts its own output, so writing the table changes the number the
  table reports and `--check` can never converge.
* `--check` tolerates small drift (see TOLERANCE). Every PR touches line counts;
  a zero-tolerance gate would make an unrelated one-line change fail CI until
  the author reran a script, which trains people to ignore the gate.

Usage:
    python scripts/render_readme_metrics.py           # rewrite the block
    python scripts/render_readme_metrics.py --check   # fail if stale (CI)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
README = REPO_ROOT / "README.md"

BEGIN = "<!-- BEGIN GENERATED METRICS -->"
END = "<!-- END GENERATED METRICS -->"

# Counts move on every PR. Regenerating is a chore, not a safety property, so
# the gate only complains once a figure is meaningfully out of date.
TOLERANCE = 0.05

_RUNTIME_GLOBS = ("arena/**/*.py", "scripts/**/*.py")
_RUNTIME_EXTRA = ("unified_bridge.py",)
_TEST_GLOBS = ("tests/**/*.py",)
_EXCLUDE = ("__pycache__", ".venv", "node_modules")


def _iter_files(globs, extra=()):
    for pattern in globs:
        for path in sorted(REPO_ROOT.glob(pattern)):
            if path.is_file() and not any(x in str(path) for x in _EXCLUDE):
                yield path
    for rel in extra:
        path = REPO_ROOT / rel
        if path.is_file():
            yield path


def _count(paths) -> tuple[int, int]:
    files = lines = 0
    for path in paths:
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        files += 1
        lines += len(text.splitlines())
    return files, lines


def collect() -> dict[str, int]:
    runtime = [p for p in _iter_files(_RUNTIME_GLOBS, _RUNTIME_EXTRA)
               if "test" not in p.name]
    tests = list(_iter_files(_TEST_GLOBS))
    rf, rl = _count(runtime)
    tf, tl = _count(tests)
    workflows = len(list((REPO_ROOT / ".github" / "workflows").glob("*.yml")))
    gates = len([p for p in (REPO_ROOT / "scripts").glob("*ratchet*.py")])
    return {
        "runtime_files": rf, "runtime_lines": rl,
        "test_files": tf, "test_lines": tl,
        "workflows": workflows, "gates": gates,
    }


def render(m: dict[str, int]) -> str:
    ratio = m["test_lines"] / m["runtime_lines"] if m["runtime_lines"] else 0.0
    return "\n".join([
        BEGIN,
        "",
        "| Metric | Value |",
        "| --- | --- |",
        f"| Runtime code | **{m['runtime_lines']:,}** lines across {m['runtime_files']:,} files |",
        f"| Test code | **{m['test_lines']:,}** lines across {m['test_files']:,} files |",
        f"| Test-to-code ratio | **{ratio:.2f}×** |",
        f"| CI workflows | **{m['workflows']}** |",
        f"| Quality gates (ratchets) | **{m['gates']}** |",
        "",
        "<sub>Generated by `scripts/render_readme_metrics.py`; CI checks this block is current.</sub>",
        "",
        END,
    ])


def _existing_block(text: str) -> str | None:
    match = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), text, re.DOTALL)
    return match.group(0) if match else None


def _numbers(block: str) -> list[int]:
    return [int(n.replace(",", "")) for n in re.findall(r"\*\*([\d,]+)\*\*", block)]


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if the rendered block is missing or stale")
    args = parser.parse_args(argv)

    text = README.read_text(encoding="utf-8")
    current = _existing_block(text)
    if current is None:
        print(f"readme metrics: FAIL -- markers {BEGIN} / {END} not found in README.md.")
        print("  Add them where the table should appear, then run this script.")
        return 1

    # Exclude the generated block itself, or the counter chases its own output.
    fresh = render(collect())

    if not args.check:
        README.write_text(text.replace(current, fresh), encoding="utf-8")
        print("readme metrics: rewritten")
        return 0

    old, new = _numbers(current), _numbers(fresh)
    if len(old) != len(new):
        print("readme metrics: FAIL -- the block's shape changed; rerun the script.")
        return 1
    stale = [
        (o, n) for o, n in zip(old, new)
        if (abs(o - n) / n if n else float(o != n)) > TOLERANCE
    ]
    if stale:
        print("readme metrics: FAIL -- figures are out of date beyond tolerance:")
        for o, n in stale:
            print(f"  README says {o:,}, actual {n:,}")
        print("  Run: python scripts/render_readme_metrics.py")
        return 1
    print(f"readme metrics: OK -- within {TOLERANCE:.0%} tolerance")
    return 0


if __name__ == "__main__":
    sys.exit(main())
