#!/usr/bin/env python3
"""v4.60.19 - Convert a spec-kit `tasks.md` into an Arena scenario JSON.

This adapter is the bridge between spec-kit (process-level) and our
scenarios runtime (execution-level). It reads the standard spec-kit
`tasks.md` format (the same one generated by `/speckit.tasks`) and
emits a JSON document that can be fed directly to our existing
`scenario.save` MCP tool.

Output format follows the spec-kit `tasks.md` format:
  - `[ ] T<id> [P?] [Story?] <tool.path>: <description>`
  - The description is a free-text sentence; the tool path is parsed
    from the leading "In `tool.path`:" or "In <tool.path>:" pattern.
  - Args are parsed from the "Args: `{...}`" line (JSON literal) or
    kept as free text (logged as a warning so we can extend parsing).
  - Placeholders `{{ steps.T0.result.field }}` are passed through
    verbatim; the scenario runtime already supports them.

Usage:
  python scripts/spec_kit_to_scenarios.py \\
      --tasks specs/001-voice-transcription/tasks.md \\
      --out voice_transcription.scenario.json \\
      --name "voice_transcription" \\
      --description "Voice -> PC -> transcribe -> chat (smoke)"

The adapter is intentionally dumb: no AST of Markdown, no fuzzy
matching. If a task line is malformed, it logs a warning and skips
the task rather than guessing.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Matches the START of a task block. A task is a single paragraph
# starting with the task id and continuing until the next task id or
# a section boundary. Supports both:
#   - [ ] T0 [P] [US1] In `mobile.record_start`: ... Args: {...} Save as x.
#   - T0 [US1] In `mobile.record_start`: ... Args: {...} Save as x.
# The first capture group is the task id (T<digits>).
# Optional "[P]" marker = parallel.
# Optional "[US<digits>]" marker = user story.
# Then a tool path (in backticks or plain) followed by colon.
TASK_START_RE = re.compile(
    r"^[\s-]*\[?\s*[xX ]?\s*\]?\s*"
    r"(?P<id>T\d+)\s+"
    r"(?:\[P\]\s+)?"
    r"(?:\[(?P<story>US\d+)\]\s+)?"
    r"In\s+"
    r"(?:`?(?P<tool>[A-Za-z_][\w.]*)`?)\s*:\s*"
)

# Matches an "Args: `{...}`" line. We can't use a regex with backrefs,
# so we do balanced-brace matching in code (see _extract_args_json).
ARGS_RE = re.compile(
    r"Args\s*:\s*`?",
    re.IGNORECASE,
)


def _extract_args_json(desc: str) -> dict | None:
    """Find the first JSON object starting at an "Args:" marker,
    using balanced-brace matching.

    Caveats:
      * Strings can contain `{{ ... }}` placeholders (scenario runtime
        template syntax). Inside a JSON string, those double braces
        must NOT count as brace depth. We treat them as zero-width
        markers: when we see `{{`, the next two chars are a
        placeholder; when we see `}}`, that closes a placeholder.
      * Backslash escapes inside JSON strings are honoured.
    """
    m = ARGS_RE.search(desc)
    if not m:
        return None
    start = m.end()
    i = start
    while i < len(desc) and desc[i] != "{":
        i += 1
    if i >= len(desc):
        return None
    depth = 0
    in_str = False
    esc = False
    j = i
    while j < len(desc):
        c = desc[j]
        # Inside a JSON string, skip over `{{...}}` placeholders so
        # their braces don't affect depth counting.
        if in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            # any other char (including `{` inside a string) is just
            # data; we keep in_str True and the depth unchanged.
            j += 1
            continue
        if c == '"':
            in_str = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                raw = desc[i:j + 1]
                try:
                    return json.loads(raw)
                except json.JSONDecodeError:
                    return None
        j += 1
    return None

# Matches a "Save as <name>." note. We support three phrasings:
#   "Save as `foo`."       (backticked)
#   "Save as foo."         (no backticks)
#   "Save the X as foo."   (the older, more flexible form)
SAVE_AS_RE = re.compile(
    r"Save\s+(?:the\s+\S+(?:\s+\S+)*?\s+)?as\s+`?(?P<name>[\w_]+)`?",
    re.IGNORECASE,
)


def parse_tasks(md_path: Path) -> list[dict]:
    """Parse a spec-kit `tasks.md` into a list of step dicts.

    A task is a single paragraph starting at the beginning of a line
    (optionally preceded by `- [ ]` or `- [x]`) and continuing until
    the next task id, a section header, or end of file. Each task
    block contains the tool path, a description, an `Args: {...}`
    JSON block, and optionally a `Save as <var>.` note.

    Returns a list of dicts:
      - id: "T0"
      - parallel: bool
      - story: "US1" or None
      - tool: "mobile.record_start"   (MCP tool name)
      - description: free text (cleaned)
      - arguments: dict (parsed from Args: JSON, or empty)
      - return_to: variable name (e.g. "recording_id"), if declared
    """
    raw = md_path.read_text(encoding="utf-8")
    lines = raw.splitlines()

    # First pass: split into "task blocks". A block starts at any
    # line that matches TASK_START_RE and continues until the next
    # such line (or end of file). Section headers (`## ...`) end a block.
    blocks: list[list[str]] = []
    current: list[str] = []
    for line in lines:
        if TASK_START_RE.match(line):
            if current:
                blocks.append(current)
            current = [line]
        elif line.lstrip().startswith("##") and current:
            blocks.append(current)
            current = []
        elif current:
            current.append(line)
    if current:
        blocks.append(current)

    # Second pass: parse each block.
    steps: list[dict] = []
    for block in blocks:
        first = block[0]
        m = TASK_START_RE.match(first)
        if not m:
            continue
        step_id = m.group("id")
        parallel = "[P]" in first
        story = m.group("story")
        tool = m.group("tool")
        # Concatenate the rest of the block as the description.
        # The first line's remainder after the tool is appended to
        # the description; the rest of the block is appended verbatim.
        first_remainder = first[m.end():].rstrip()
        rest = "\n".join(line.rstrip() for line in block[1:]).strip()
        desc = (first_remainder + ("\n" + rest if rest else "")).strip()

        # Extract JSON args from "Args: `{...}`" via balanced-brace parsing.
        arguments: dict = {}
        parsed_args = _extract_args_json(desc)
        if parsed_args is not None:
            arguments = parsed_args
        elif "Args" in desc:
            print(
                f"[WARN] {step_id}: 'Args' marker found but no valid JSON "
                f"object parsed; leaving arguments empty.",
                file=sys.stderr,
            )

        # Extract "Save as <name>." note.
        return_to: str | None = None
        sm = SAVE_AS_RE.search(desc)
        if sm:
            return_to = sm.group("name")

        steps.append(
            {
                "id": step_id,
                "parallel": parallel,
                "story": story,
                "tool": tool,
                "description": desc,
                "arguments": arguments,
                "return_to": return_to,
            }
        )
    return steps


def build_scenario(
    steps: list[dict],
    *,
    name: str,
    description: str,
) -> dict:
    """Convert parsed steps into an Arena `scenario.save` JSON document.

    The shape matches the schema documented in
    `arena/scenarios/storage.py`: top-level keys `name`, `description`,
    `steps` (list of step dicts), plus a `final` value derived from
    the last non-skip step's return_to.
    """
    scenario_steps: list[dict] = []
    for s in steps:
        step_doc: dict = {
            "id": s["id"],
            "tool": s["tool"],
            "arguments": s["arguments"],
        }
        if s["return_to"]:
            # Map "Save ... as foo" -> the step's result is bound to
            # `steps.T<id>.result`; scenarios already support
            # `{{ steps.<id>.result.<field> }}` placeholders, so we
            # don't need a separate "bind" key in this version. We
            # surface the binding in `description` for human review.
            step_doc["description"] = (
                f"{s['description']}  [result -> {s['return_to']}]"
            )
        else:
            step_doc["description"] = s["description"]
        if s["parallel"]:
            step_doc["parallel"] = True
        if s["story"]:
            step_doc["story"] = s["story"]
        scenario_steps.append(step_doc)

    # The `final` value: prefer a dedicated "final/return" step
    # (whose `tool` name is `scenario.return` or similar). Fall back
    # to the last step with `return_to`. The smoke runner can
    # override this.
    final_step = next(
        (s for s in reversed(steps)
         if s["tool"] in {"scenario.return", "scenario.final"}),
        None,
    )
    if final_step:
        # Use the final step's own text/value argument as the
        # scenario's `final`. Pass it through verbatim (placeholders
        # resolve at scenario-run time).
        final = dict(final_step["arguments"])
    else:
        last_return = next(
            (s for s in reversed(steps) if s.get("return_to")), None
        )
        if last_return:
            final = {"text": f"{{{{ steps.{last_return['id']}.result.text }}}}"}
        else:
            final = {"text": "Scenario completed (no return_to declared)."}

    return {
        "name": name,
        "description": description,
        "version": "1",
        "steps": scenario_steps,
        "final": final,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1] if __doc__ else "")
    ap.add_argument("--tasks", required=True, type=Path,
                    help="Path to spec-kit tasks.md")
    ap.add_argument("--out", required=True, type=Path,
                    help="Output scenario JSON path")
    ap.add_argument("--name", required=True,
                    help="Scenario name (used in scenario.save)")
    ap.add_argument("--description", default="",
                    help="Scenario description")
    args = ap.parse_args()

    if not args.tasks.exists():
        print(f"[ERR] tasks file not found: {args.tasks}", file=sys.stderr)
        return 2

    steps = parse_tasks(args.tasks)
    if not steps:
        print(f"[ERR] no tasks parsed from {args.tasks}", file=sys.stderr)
        return 3

    scenario = build_scenario(
        steps,
        name=args.name,
        description=args.description or f"Generated from {args.tasks}",
    )
    args.out.write_text(
        json.dumps(scenario, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(
        f"[OK] wrote {args.out} "
        f"({len(scenario['steps'])} steps from {len(steps)} tasks)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
